version: '3.4'

services:
  media.api:
    image: ${DOCKER_REGISTRY-}mediaapi
    build:
      context: .
      dockerfile: src/Services/Media/Media.API/Dockerfile

  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Authentication.API/Dockerfile

