version: '3.4'

services:
  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: src/Services/Authentication/Authentication.API/Dockerfile

  media.api:
    image: ${DOCKER_REGISTRY-}mediaapi
    build:
      context: .
      dockerfile: src/Services/Media/Media.API/Dockerfile

